import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import {DatabaseSync} from 'node:sqlite';
process.chdir(new URL('..',import.meta.url).pathname);const sqlite=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const db={prepare(sql){function bound(v){return {async first(){return sqlite.prepare(sql).get(...v)??null},async run(){return sqlite.prepare(sql).run(...v)},async all(){return {results:sqlite.prepare(sql).all(...v)}}}}return {...bound([]),bind(...v){return bound(v)}}},async batch(list){sqlite.exec('BEGIN');try{for(const s of list)await s.run();sqlite.exec('COMMIT');}catch(e){sqlite.exec('ROLLBACK');throw e;}}};const objects=new Map();const bucket={async put(k,b){objects.set(k,new Uint8Array(b).slice())},async get(k){const b=objects.get(k);return b?{async arrayBuffer(){return b.slice().buffer}}:null}};globalThis.testStorage={db,bucket};
const url=s=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64');const tse=url(fs.readFileSync('lib/tse.ts','utf8')),audit=url(fs.readFileSync('lib/audit.ts','utf8'));const mod=await import(url(fs.readFileSync('lib/archive.ts','utf8').replace("import {getStorage} from '../db';",'const getStorage=()=>globalThis.testStorage;').replace("from './tse'",'from '+JSON.stringify(tse)).replace("from './audit'",'from '+JSON.stringify(audit))));
let raw;globalThis.fetch=async()=>Response.json(raw);
const fixture=(id,time,votes)=>({f:'o',t:'1',ele:'6257',cdabr:'BR',tpabr:'br',idg:id,dg:'04/10/2026',hg:time,dt:'04/10/2026',ht:time,dv:'s',and:'p',s:{pst:'20,00',st:'20',ts:'100'},v:{tv:'1000',vv:'900',vb:'50',tvn:'50'},carg:[{cd:'1',agr:[{par:[{sg:'TESTE',cand:votes.map(([id,v])=>({sqcand:id,n:id,nmu:'Fixture '+id,vap:String(v),pvap:'10,00',st:'Concorrendo',dvt:'Válido'}))}]}]}],unknown:{preserved:true}});
async function collect(f){raw=f;sqlite.exec('UPDATE source_state SET next_ms=0,lease_until=0');return await mod.collect('BR','1');}
const a=await collect(fixture('1','17:00:00',[['1',100],['2',80]]));assert.equal(a.error,null);assert.ok(a.result.candidates[0].photo.endsWith('/fotos/br/1.jpeg'));assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM audit_events').get().n,2);
const b=await collect(fixture('2','17:01:00',[['1',120],['2',75]]));assert.equal(b.error,null);assert.equal(sqlite.prepare("SELECT delta FROM audit_events WHERE kind='aumento'").get().delta,20);assert.equal(sqlite.prepare("SELECT delta FROM audit_events WHERE kind='reducao'").get().delta,-5);
const c=await collect(fixture('2','17:01:00',[['1',110]]));assert.equal(c.result.candidates[0].votes,110);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM audit_events WHERE kind='mesmo_idg'").get().n,1);const missing=sqlite.prepare("SELECT * FROM audit_events WHERE kind='candidato_ausente'").get();assert.equal(missing.before_votes,75);assert.equal(missing.after_votes,null);assert.equal(missing.delta,null);
const old=await collect(fixture('1','17:00:00',[['1',100],['2',80]]));assert.equal(old.result.candidates[0].votes,110);assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM audit_events WHERE kind='geracao_anterior'").get().n,1);
const count=sqlite.prepare('SELECT COUNT(*) n FROM audit_events').get().n;await collect(fixture('2','17:01:00',[['1',110]]));assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM audit_events').get().n,count);
let route=fs.readFileSync('app/api/auditoria/route.ts','utf8').replace("import {getStorage} from '../../../db';",'const getStorage=()=>globalThis.testStorage;').replace("from '../../../lib/tse'",'from '+JSON.stringify(tse));const {GET}=await import(url(route));const response=await GET(new Request('https://test/api/auditoria?uf=BR&cargo=1&candidate=1'));const result=await response.json();assert.equal(result.records.length,3);assert.ok(result.records[0].hash);assert.ok(result.records[0].previous_hash);assert.ok(result.records[0].received.endsWith('Z'));assert.equal(result.records[0].delta,-10);const alerts=await (await GET(new Request('https://test/api/auditoria?uf=BR&cargo=1&alerts=1'))).json();assert.equal(alerts.records.length,5);
assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM snapshots').get().n,3);for(const s of sqlite.prepare('SELECT * FROM snapshots').all())assert.equal(JSON.parse(new TextDecoder().decode(objects.get(s.object_key))).unknown.preserved,true);
console.log('PASS: persistent increases, reductions, missing candidates, same-IDG content change, stale response, unchanged duplicate, candidate history, alert filter, evidence hashes and original bytes.');

// A slow source preserves the published version, records the original failure, and releases its lease.
const originalTimeout=AbortSignal.timeout;let timeoutMs=0;AbortSignal.timeout=ms=>{timeoutMs=ms;return new AbortController().signal;};
globalThis.fetch=async()=>{throw new DOMException('The operation was aborted due to timeout','TimeoutError');};
sqlite.exec('UPDATE source_state SET next_ms=0,lease_until=0');const failed=await mod.collect('BR','1');assert.equal(timeoutMs,20000);assert.equal(failed.result.candidates[0].votes,110);assert.ok(failed.error.includes('Nova tentativa automática em 5 segundos'));assert.ok(failed.nextPoll>4000&&failed.nextPoll<=5000);
const state=sqlite.prepare('SELECT * FROM source_state').get();assert.equal(state.lease,null);assert.equal(state.lease_until,0);const failure=sqlite.prepare('SELECT * FROM collection_logs ORDER BY id DESC LIMIT 1').get();assert.equal(failure.state,'erro_coleta');assert.equal(failure.error,'The operation was aborted due to timeout');
globalThis.fetch=async()=>Response.json(raw);const recovered=await collect(fixture('3','17:02:00',[['1',130]]));assert.equal(recovered.error,null);assert.equal(recovered.result.candidates[0].votes,130);
globalThis.fetch=async()=>new Response('Rate limit',{status:429});sqlite.exec('UPDATE source_state SET next_ms=0,lease_until=0');const limited=await mod.collect('BR','1');assert.ok(limited.nextPoll>600000);assert.equal(limited.result.candidates[0].votes,130);AbortSignal.timeout=originalTimeout;
console.log('PASS: 20-second source deadline, timeout log, 5-second retry, unchanged results during failure, released lease, recovery and preserved 429 cooldown.');
