import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText;
const resolve=s=>{for(const name of ['react','react/jsx-runtime','lucide-react'])s=s.replaceAll(`'${name}'`,JSON.stringify(import.meta.resolve(name))).replaceAll(`"${name}"`,JSON.stringify(import.meta.resolve(name)));return s;};
const avatar=url(resolve(compile('app/CandidateAvatar.tsx')));const {default:Card}=await import(url(resolve(compile('app/ResultCandidate.tsx')).replace("'./CandidateAvatar'",JSON.stringify(avatar))));
const candidate=(id,votes,percent)=>({id,name:'Candidato '+id,number:id,party:'PARTIDO',votes,percent,status:'',destination:'',elected:false,photo:'/official-'+id+'.jpeg'});
for(const cargo of ['1','3','5','6','7','8']){const cards=[candidate('1',60,60),candidate('2',30,30),candidate('3',10,10)].map((c,i)=>React.createElement(Card,{candidate:c,rank:i+1,leader:i<2,uf:'ES',cargo,key:c.id}));const html=renderToStaticMarkup(React.createElement('section',null,cards));assert.equal((html.match(/<img /g)||[]).length,2);assert.equal((html.match(/candidate-avatar/g)||[]).length,2);assert.ok(!html.includes('src="/official-3.jpeg"'));assert.ok(html.includes('cargo='+cargo));}
const zero=renderToStaticMarkup(React.createElement(Card,{candidate:candidate('1',0,0),rank:1,leader:false,uf:'ES',cargo:'3'}));assert.ok(!zero.includes('<img'));assert.ok(!zero.includes('1º lugar'));
const presidential=url(compile('lib/presidential.ts'));const {ranking}=await import(presidential);const ranked=ranking([candidate('1',60,60),candidate('2',30,30),candidate('3',10,10)]);const filtered=ranked.filter(r=>r.candidate.id==='3');assert.equal(filtered[0].rank,3);assert.equal(filtered[0].index,2);
let home=resolve(compile('app/page.tsx'));home=home.replace("'./CandidateAvatar'",JSON.stringify(avatar)).replace("'../lib/presidential'",JSON.stringify(presidential));for(const name of ['SiteHeader','UrnPump'])home=home.replace(`'./${name}'`,JSON.stringify(url('export default function(){return null}')));
const stub=url(`export default function(){return {data:globalThis.leaderData,loading:false}}`);home=home.replace("'./usePresidential'",JSON.stringify(stub));const {default:Home}=await import(url(home));
globalThis.leaderData={result:{id:'1',candidates:ranked.map(r=>r.candidate),valid:100,blank:0,nullVotes:0,progress:10,sections:1,totalSections:10,status:'Apuração em andamento'}};const html=renderToStaticMarkup(React.createElement(Home));assert.equal((html.match(/<img /g)||[]).length,2);assert.equal((html.match(/race-front/g)||[]).length,2);assert.equal((html.match(/race-compact/g)||[]).length,1);
globalThis.leaderData.result.candidates=ranked.map(r=>({...r.candidate,votes:0,percent:0}));globalThis.leaderData.result.valid=0;const empty=renderToStaticMarkup(React.createElement(Home));assert.ok(!empty.includes('<img'));assert.ok(!empty.includes('race-rank'));
console.log('PASS: 2 circular avatars across all six cargos and home; remaining candidates have no photo; 0% has no placement; filtering preserves original ranking.');
