import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
process.chdir(new URL('..',import.meta.url).pathname);
const src=ts.transpileModule(fs.readFileSync('lib/presidential.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const {ranking,overtakes,runoff,positionChanges,hasPlacement}=await import('data:text/javascript;base64,'+Buffer.from(src).toString('base64'));
const c=(id,votes,percent=0)=>({id,name:'Fixture '+id,number:id,party:'TEST',votes,percent,status:'',destination:'Válido',elected:false});
const result=(list,valid=1000,status='Apuração em andamento')=>({id:'1',generated:'04/10/2026 17:10:00',generationTime:1,totalization:'',progress:50,sections:50,totalSections:100,total:1200,valid,blank:100,nullVotes:100,status,candidates:list});
let r=runoff(result([c('A',500,50),c('B',300,30),c('C',200,20)]));assert.equal(r.mode,'runoff');assert.deepEqual(r.ids,['A','B']);assert.equal(r.final,false);
r=runoff(result([c('A',501,50.00),c('B',299,29.90),c('C',200,20)]));assert.equal(r.mode,'majority');assert.deepEqual(r.ids,['A']);assert.equal(r.threshold,501);
assert.equal(runoff(result([c('A',500,50.01),c('B',300),c('C',200)])).mode,'runoff');
assert.equal(runoff(result([c('A',500),c('B',299),c('C',200)],999)).mode,'majority');
assert.equal(runoff(result([c('A',0),c('B',0)],0)).mode,'waiting');
assert.equal(runoff(result([c('A',600),c('B',400)],1000,'Divulgação ainda não liberada')).mode,'waiting');
r=runoff(result([c('A',400),c('B',300),c('C',300)]));assert.equal(r.tied,true);assert.deepEqual(r.ids,['A','B','C']);
r=runoff(result([c('A',450),c('B',350),c('C',200)],1000,'Totalização finalizada'));assert.equal(r.final,true);assert.deepEqual(r.ids,['A','B']);
const before=[c('A',100),c('B',90),c('C',50)];const after=[c('A',101),c('B',110),c('C',50)];assert.deepEqual(ranking(after).map(x=>x.candidate.id),['B','A','C']);let moves=overtakes(before,after);assert.equal(moves.length,1);assert.equal(moves[0].id,'B');assert.equal(moves[0].rank,1);assert.deepEqual(moves[0].passed,['Fixture A']);
assert.deepEqual(overtakes(before,before),[]);assert.deepEqual(overtakes([],after),[]);assert.deepEqual(overtakes(before,[c('A',100),c('B',100),c('C',50)]),[]);
assert.deepEqual(ranking([c('B',100),c('A',100),c('C',90)]).map(x=>[x.candidate.id,x.rank]),[['A',1],['B',1],['C',3]]);
moves=overtakes(before,[c('A',100),c('B',90),c('C',120)]);assert.equal(moves[0].id,'C');assert.equal(moves[0].passed.length,2);
assert.deepEqual(before.map(x=>x.id),['A','B','C']);
console.log('PASS: strict majority, 50% boundary and rounded percentages, valid votes denominator, partial/final states, missing/zero data, runoff ties, shared ranks, overtakes and multi-position jumps.');

assert.equal(hasPlacement(c('A',0,0)),false);assert.equal(hasPlacement(c('A',10,0)),false);assert.equal(hasPlacement(c('A',10,0.01)),true);
const previous=[c('A',100,10),c('B',90,9),c('C',50,5)];
assert.deepEqual(positionChanges(previous,[c('A',101,10.1),c('B',91,9.1),c('C',51,5.1)]),[]);
let movements=positionChanges(previous,[c('A',101,10.1),c('B',110,11),c('C',50,5)]);assert.equal(movements.find(m=>m.id==='B').direction,'up');assert.equal(movements.find(m=>m.id==='A').direction,'down');assert.equal(movements.length,2);
assert.deepEqual(positionChanges([],previous),[]);assert.deepEqual(positionChanges(previous,previous),[]);
assert.deepEqual(positionChanges(previous,[c('A',100,10),c('B',100,10),c('C',50,5)]),[]);
assert.deepEqual(positionChanges(previous,[c('A',100,0),c('B',110,0),c('C',50,0)]),[]);
console.log('PASS: placement hidden at 0%, no movement on initial/unchanged/order-preserving updates, and paired up/down movement only on overtaking.');
