'use client';
import {useRound} from './RoundProvider';
import {roundFetch} from '../lib/round-client';
import {useEffect,useState} from 'react';
import {Download,LockKeyhole,Archive} from 'lucide-react';
type Status={count:number;bytes:number;pending:number;missingFiles:number;indicesCompleted:number;indicesTotal:number;collectionComplete:boolean;phase:string;packedFiles:number;zipBytes:number|null;ready:boolean;error:string|null};
const size=(bytes:number)=>{if(!bytes)return '0 B';const i=Math.min(4,Math.floor(Math.log(bytes)/Math.log(1024)));return `${(bytes/1024**i).toLocaleString('pt-BR',{maximumFractionDigits:2})} ${['B','KB','MB','GB','TB'][i]}`;};
export default function ArchiveDownload(){const electionRound=useRound();const [data,setData]=useState<Status|null>(null),[error,setError]=useState('');useEffect(()=>{let active=true,timer:ReturnType<typeof setTimeout>;const controller=new AbortController();async function read(){try{const r=await roundFetch('/api/acervo/zip',{cache:'no-store',signal:controller.signal});const d=await r.json() as Status;if(!r.ok)throw Error(d.error??'Falha ao consultar pacote.');if(active){setData(d);setError('');}}catch(e){if(active)setError(e instanceof Error?e.message:'Falha ao consultar acervo.');}finally{if(active)timer=setTimeout(read,15000);}}read();return()=>{active=false;controller.abort();clearTimeout(timer);};},[]);
 return <section className="archive-download" aria-labelledby="archive-download-title"><div className="archive-download-heading"><Archive size={23} aria-hidden="true"/><div><span className="eyebrow">ACERVO COMPLETO · {electionRound}º TURNO - 2026</span><h2 id="archive-download-title">Download dos arquivos do TSE</h2></div></div><p>Pacote ZIP com os originais obtidos pelo site: resultados, municípios, BU, RDV, logs de urna, índices e respostas arquivadas. Cópias idênticas compartilhadas são incluídas uma única vez.</p><div className="archive-download-stats"><div><span>Arquivos obtidos</span><strong>{data?data.count.toLocaleString('pt-BR'):'—'}</strong></div><div><span>Tamanho dos originais</span><strong>{data?size(data.bytes):'—'}</strong></div><div><span>Índices concluídos</span><strong>{data?`${data.indicesCompleted} / ${data.indicesTotal}`:'—'}</strong></div></div>{error||data?.error?<p className="alert" role="alert">{error||data?.error}</p>:null}<div className="archive-download-status" role="status">{!data?'Consultando o acervo…':data.ready?`ZIP pronto · ${size(data.zipBytes??0)}`:data.collectionComplete?`Preparando o ZIP: ${data.packedFiles.toLocaleString('pt-BR')} de ${data.count.toLocaleString('pt-BR')} arquivos incluídos.`:`Aguardando conclusão: ${data.pending.toLocaleString('pt-BR')} tarefas de coleta e ${data.missingFiles.toLocaleString('pt-BR')} arquivos anunciados ainda não arquivados.`}</div>{data?.ready?<a className="archive-download-button" href="/api/acervo/zip?download=1"><Download size={17}/>Baixar acervo completo (.zip)</a>:<button type="button" disabled><LockKeyhole size={16}/>Download disponível após conclusão</button>}<small>O ZIP só começa a ser gerado após todos os índices e downloads terminarem. Falhas e novas tentativas mantêm o botão bloqueado. O pacote inclui todo o acervo, independentemente dos filtros desta página.</small></section>;
}
