'use client';
import {roundFetch} from '../lib/round-client';
import {useEffect,useState} from 'react';
import CandidateStatus from './CandidateStatus';
import {candidateStatus} from '../lib/candidate-status';
import type {Result} from '../lib/tse';
type RecordRow={composition?:{sources:{uf:string;snapshotId:number;hash:string;received:string;generated:string}[]};id:number;idg:string;generated:string;totalization:string;received:string;saved:string;hash:string};
const local=(iso:string)=>new Date(iso).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'});
export default function History({uf,cargo,includeExterior=true,version}:{uf:string;cargo:string;includeExterior?:boolean;version?:number}){
 const [rows,setRows]=useState<RecordRow[]>([]),[next,setNext]=useState<number|null>(null),[error,setError]=useState(''),[detail,setDetail]=useState<{result:Result;archive:RecordRow}|null>(null),[busy,setBusy]=useState(false);
 const base=`/api/historico?uf=${uf}&cargo=${cargo}&exterior=${includeExterior?1:0}`;
 useEffect(()=>{let active=true;setRows([]);setDetail(null);setNext(null);setError('');roundFetch(base,{cache:'no-store'}).then(async r=>{const j:any=await r.json();if(!r.ok)throw Error(j.error);if(active){setRows(j.records);setNext(j.next);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[base,version]);
 async function more(){setBusy(true);try{const r=await roundFetch(`${base}&before=${next}`,{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw Error(j.error);setRows(a=>[...a,...j.records]);setNext(j.next);}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function select(id:number){setError('');try{const r=await roundFetch(`${base}&id=${id}`,{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw Error(j.error);setDetail(j);}catch(e){setError(String(e));}}
 return <section className="panel history"><div className="panel-title"><div><span className="eyebrow">ARQUIVO PERSISTENTE · {uf==='ZZ'?'EXTERIOR':uf}</span><h2>Consultar atualizações anteriores</h2></div></div><p className="history-help">{uf==='BR'&&cargo==='1'&&!includeExterior?'Brasil sem exterior: cada composição reúne 27 versões estaduais com seus IDs, hashes e horários. Os percentuais são calculados pelo site. ':uf==='BR'?'Brasil + exterior usa o arquivo nacional do TSE. ':''}Cada versão recebida é preservada com o arquivo original, identificação do TSE e horários. Recebimento e armazenamento abaixo em Brasília (UTC−3).</p>{error&&<p className="alert" role="alert">{error}</p>}
 {rows.length?<div className="history-table"><table><thead><tr><th>Geração no TSE</th><th>Totalização no TSE</th><th>Recebido pelo site</th><th>Consulta</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.generated}<small>IDG {r.idg}</small></td><td>{r.totalization||'Não informado'}</td><td>{local(r.received)}<small>Salvo: {local(r.saved)}</small></td><td><button onClick={()=>select(r.id)}>Ver versão</button><a href={`${base}&id=${r.id}&download=1`}>Baixar JSON</a></td></tr>)}</tbody></table></div>:<div className="history-help">{error?'Arquivo indisponível.':'Nenhuma versão arquivada para esta seleção. O histórico começa na primeira coleta bem-sucedida.'}</div>}
 {next&&<button className="history-more" disabled={busy} onClick={more}>{busy?'Carregando…':'Carregar versões anteriores'}</button>}
 {detail&&<div className="history-detail"><div className="panel-title"><h2>Versão arquivada · {detail.result.generated}</h2><button onClick={()=>setDetail(null)}>Fechar</button></div><p>Recebida: {local(detail.archive.received)} · Seções totalizadas: {detail.result.progress.toLocaleString('pt-BR')}%</p><div className="history-table"><table><thead><tr><th>Candidato</th><th>Votos</th><th>Percentual</th><th>Destinação / situação</th></tr></thead><tbody>{detail.result.candidates.map(c=><tr key={c.id}><td>{c.name}<small>{c.party} · {c.number}</small></td><td>{c.votes.toLocaleString('pt-BR')}</td><td>{c.percent.toLocaleString('pt-BR')}%</td><td><CandidateStatus candidate={c}/>{[c.destination,candidateStatus(c)?'':c.status].filter(Boolean).join(' · ')}</td></tr>)}</tbody></table></div><p className="hash">{detail.archive.composition?.sources.map(source=><a key={source.uf} href={`/api/historico?uf=${source.uf}&cargo=1&id=${source.snapshotId}&download=1`}>{source.uf} · versão #{source.snapshotId} · recebido {local(source.received)}<br/></a>)}SHA-256: {detail.archive.hash}</p></div>}
 <p className="history-help">O hash permite conferir a integridade da cópia arquivada. A assinatura digital do TSE não é verificada nesta versão. O horário de inserção de cada voto não está disponível nos arquivos acumulados.</p></section>;
}
