'use client';
import {roundFetch} from '../lib/round-client';
import {useEffect,useRef,useState} from 'react';
type Log={id:number;state:string;http:number|null;started:string;received:string|null;finished:string|null;generated:string|null;totalization:string|null;size:number|null;latency:number|null;idg:string|null;snapshot_id:number|null;error:string|null;hash:string|null};
const states:Record<string,string>={municipio_sem_alteracao:'Município · sem alteração',municipio_versao_arquivada:'Versão municipal arquivada',municipio_geracao_anterior:'Município · geração anterior preservada',consultando:'Consultando',resposta_arquivada:'Resposta arquivada',versao_inserida:'Versão inserida',versao_repetida:'Versão repetida',sem_alteracao:'Sem alteração (304)',erro_http:'Erro HTTP',nao_publicado:'Rejeitada pela validação / falha ao gravar',erro_coleta:'Falha na coleta',arquivo_urna_salvo:'Arquivo de urna salvo'};
const date=(s:string|null)=>s?new Date(s).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',fractionalSecondDigits:3}):'—';
export default function Logs({uf,cargo}:{uf:string;cargo:string}){
 const [rows,setRows]=useState<Log[]>([]),[error,setError]=useState(''),[next,setNext]=useState<number|null>(null),[detail,setDetail]=useState<unknown>(null),[selected,setSelected]=useState<number|null>(null),[moreLoading,setMoreLoading]=useState(false);
 const [detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState('');
 const dialog=useRef<HTMLDialogElement|null>(null),detailRequest=useRef<AbortController|null>(null),activeDetail=useRef<number|null>(null);
 const closeDetail=()=>{activeDetail.current=null;detailRequest.current?.abort();setSelected(null);setDetail(null);setDetailLoading(false);setDetailError('');};
 const base=`/api/logs?uf=${uf}&cargo=${cargo}`;const activeScope=useRef(base);activeScope.current=base;
 useEffect(()=>{setRows([]);setNext(null);closeDetail();setError('');},[base]);
 useEffect(()=>{const element=dialog.current;if(!element)return;if(selected!==null&&!element.open)element.showModal();else if(selected===null&&element.open)element.close();},[selected]);
 useEffect(()=>()=>detailRequest.current?.abort(),[]);
 useEffect(()=>{let active=true;const controller=new AbortController();
 async function refresh(){try{const r=await roundFetch(base,{cache:'no-store',signal:controller.signal});const j:any=await r.json();if(!r.ok)throw Error(j.error);if(!active)return;setError('');setRows(old=>{const map=new Map(old.map(x=>[x.id,x]));for(const row of j.records)map.set(row.id,row);return [...map.values()].sort((a,b)=>b.id-a.id);});setNext(old=>old??j.next);

 }catch(e){if(active)setError(e instanceof Error?e.message:'Falha ao consultar logs.');}}
 refresh();return()=>{active=false;controller.abort();};},[base]);
 async function more(){const scope=base;setMoreLoading(true);try{const r=await roundFetch(`${base}&before=${rows.at(-1)?.id??next}`,{cache:'no-store'});const j:any=await r.json();if(!r.ok)throw Error(j.error);if(activeScope.current!==scope)return;setRows(old=>{const map=new Map(old.map(x=>[x.id,x]));for(const row of j.records)map.set(row.id,row);return [...map.values()].sort((a,b)=>b.id-a.id);});setNext(j.next);}catch(e){if(activeScope.current===scope)setError(String(e));}finally{setMoreLoading(false);}}
 async function inspect(id:number){const scope=base;detailRequest.current?.abort();const controller=new AbortController();detailRequest.current=controller;activeDetail.current=id;setSelected(id);setDetail(null);setDetailError('');setDetailLoading(true);try{const r=await roundFetch(`${base}&id=${id}`,{cache:'no-store',signal:controller.signal});const j:any=await r.json();if(!r.ok)throw Error(j.error??'Falha ao abrir o conteúdo.');if(activeScope.current===scope&&activeDetail.current===id)setDetail(j);}catch(e){if(!controller.signal.aborted&&activeScope.current===scope&&activeDetail.current===id)setDetailError(e instanceof Error?e.message:'Falha ao abrir o conteúdo.');}finally{if(!controller.signal.aborted&&activeScope.current===scope&&activeDetail.current===id)setDetailLoading(false);}}
 return <section className="panel logs"><div className="panel-title"><div><span className="eyebrow">REGISTRO PERSISTENTE · {uf==='ZZ'?'EXTERIOR':uf}</span><h2>Logs de coleta e inserção</h2></div></div><p className="history-help">Acervo encerrado do 1º turno - 2026. Horários do servidor em Brasília (UTC−3), com milissegundos.</p>{error&&<p className="alert" role="alert">{error}</p>}
 <div className="history-table"><table><thead><tr><th>Registro / estado</th><th>Consulta iniciada</th><th>Resposta recebida</th><th>Gravação / processamento concluído</th><th>Origem e tamanho</th><th>Detalhes</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>#{r.id}</strong><small className={r.error?'log-error':''}>{states[r.state]??r.state}</small>{r.error&&<small>{r.error}</small>}</td><td>{date(r.started)}</td><td>{date(r.received)}<small>Geração TSE: {r.generated??'—'}</small><small>Totalização TSE: {r.totalization??'—'}</small></td><td>{date(r.finished)}<small>{r.snapshot_id?`Versão arquivada #${r.snapshot_id}`:cargo==='urna'?'Arquivo técnico':cargo==='municipal'&&r.state.startsWith('municipio_')?'Versão municipal preservada':'Sem versão publicada'}</small></td><td>{r.http?`HTTP ${r.http}`:'—'}<small>{r.size==null?'Sem corpo arquivado':`${r.size.toLocaleString('pt-BR')} bytes`}</small><small>{r.latency==null?'':`${r.latency} ms`}</small><small>IDG: {r.idg??'—'}</small></td><td><button onClick={()=>inspect(r.id)}>Ver conteúdo</button><a href={`${base}&id=${r.id}&download=json`}>Baixar log completo</a>{r.hash&&<a href={`${base}&id=${r.id}&download=raw`}>Resposta original</a>}</td></tr>)}</tbody></table></div>
 {!rows.length&&<p className="history-help">Nenhuma coleta registrada para esta seleção desde a implantação dos logs.</p>}{next&&<button className="history-more" disabled={moreLoading} onClick={more}>{moreLoading?'Carregando…':'Carregar registros anteriores'}</button>}
 <dialog ref={dialog} className="log-content-dialog" aria-labelledby="log-content-title" onCancel={closeDetail}><div className="log-dialog-heading"><div><span className="eyebrow">RESPOSTA ARQUIVADA</span><h2 id="log-content-title">Conteúdo do log #{selected}</h2></div><button type="button" onClick={closeDetail} autoFocus>Fechar</button></div>{detailLoading&&<p className="log-dialog-message" role="status">Abrindo conteúdo arquivado…</p>}{detailError&&<div className="log-dialog-message"><p role="alert" className="alert">{detailError}</p><button onClick={()=>selected!==null&&inspect(selected)}>Tentar novamente</button></div>}{detail!==null&&<><div className="log-dialog-actions"><a href={`${base}&id=${selected}&download=json`}>Baixar log completo</a><a href={`${base}&id=${selected}`} target="_blank" rel="noreferrer">Abrir JSON em outra aba</a></div><pre tabIndex={0} aria-label="Conteúdo completo do log">{JSON.stringify(detail,null,2)}</pre></>}</dialog>
 <p className="history-help">São registrados os acessos efetivamente feitos ao endpoint e seus resultados. Uma resposta 304 não traz novo corpo. Respostas repetidas usam a mesma cópia pelo hash, com um log por consulta. A coleta do 1º turno - 2026 está encerrada. Versões que não foram recebidas não podem ser reconstruídas. Logs anteriores à implantação desta área não existem.</p></section>;
}
