'use client';
import {useRound} from './RoundProvider';
import SecondPump from './SecondPump';
import CandidateStatus from './CandidateStatus';
import {candidateStatus} from '../lib/candidate-status';
import {useLayoutEffect,useRef,useState} from 'react';
import {Activity,ArrowUp,ArrowDown,Clock3,Radio,ShieldCheck,History,ArrowUpRight} from 'lucide-react';
import SiteHeader from './SiteHeader';
import CandidateAvatar from './CandidateAvatar';
import UrnPump from './UrnPump';
import usePresidential,{type PresidentialData} from './usePresidential';
import {positionChanges,hasPlacement,ranking,runoff} from '../lib/presidential';
import type {Candidate} from '../lib/tse';
const number=(n:number)=>n.toLocaleString('pt-BR');
const percentage=(n:number)=>n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function Home({initialData=null}:{initialData?:PresidentialData|null}){const electionRound=useRound();
 const {data,loading}=usePresidential(initialData);const result=data?.result??null;const ranked=ranking(result?.candidates??[]);const round=runoff(result);const version=data?.archive?.hash??result?.id??'';
 const old=useRef<Candidate[]|null>(null),elements=useRef(new Map<string,HTMLElement>()),positions=useRef(new Map<string,{top:number;left:number}>());
 const [movement,setMovement]=useState<ReturnType<typeof positionChanges>>([]),[changes,setChanges]=useState<Record<string,number>>({}),[notice,setNotice]=useState('');
 useLayoutEffect(()=>{if(!result)return;const before=old.current;const movements=before?positionChanges(before,result.candidates):[];setMovement(movements);
 if(before){const last=new Map(before.map(c=>[c.id,c.votes]));setChanges(Object.fromEntries(result.candidates.filter(c=>last.has(c.id)).map(c=>[c.id,c.votes-last.get(c.id)!])));}
 setNotice(movements.map(m=>`${result.candidates.find(c=>c.id===m.id)?.name}: ${m.direction==='up'?'subiu':'desceu'} no ranking.`).join(' '));
 const next=new Map<string,{top:number;left:number}>();const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;const moving=new Set(movements.map(m=>m.id));
 for(const {candidate:c} of ranked){const element=elements.current.get(c.id);if(!element)continue;for(const animation of element.getAnimations())animation.cancel();const rect=element.getBoundingClientRect(),position={top:rect.top+window.scrollY,left:rect.left+window.scrollX};const previous=positions.current.get(c.id);next.set(c.id,position);if(previous&&moving.has(c.id)&&!reduced){const x=previous.left-position.left,y=previous.top-position.top;if(x||y)element.animate([{transform:`translate(${x}px,${y}px)`,zIndex:3},{transform:'translate(0,0)',zIndex:3}],{duration:800,easing:'cubic-bezier(.2,.8,.2,1)'});}}
 positions.current=next;old.current=result.candidates;
 },[version]);
 const majority=round.mode==='majority';const roundNames=ranked.filter(({candidate})=>round.ids.includes(candidate.id)).map(({candidate})=>candidate.name);
 return <main className="president-home"><UrnPump/><SecondPump/><SiteHeader active="presidente"/><div className="president-workspace"><div className="race-title"><div><p className="eyebrow">{electionRound===2?'25 OUT 2026 · 2º TURNO · BRASIL E EXTERIOR':'04 OUT 2026 · 1º TURNO · BRASIL E EXTERIOR'}</p><h1>Presidente da República</h1></div><div className={`race-connection ${data?.error?'race-offline':''}`}><Radio size={16}/>{loading?'Carregando acervo':data?.error?'Atualização indisponível':electionRound===2?'2º turno · atualização automática':'1º turno encerrado'}</div></div>
 {data?.error&&<div className="alert" role="alert"><strong>Não foi possível atualizar.</strong> {data.error} {result&&'Últimos totais recebidos preservados.'}</div>}
 <section className="race-progress" aria-label="Progresso da apuração"><div><span><Activity size={16}/> Seções totalizadas</span><strong>{result?percentage(result.progress):'—'}%</strong></div><div className="race-track"><i style={{width:`${Math.min(100,result?.progress??0)}%`}}/></div><div className="race-progress-meta"><span>{result?`${number(result.sections)} de ${number(result.totalSections)} seções`:'Aguardando publicação oficial'}</span><span>{result?.status??'Sem resultados recebidos'}</span></div></section>
 {electionRound===2&&<section className="round-banner"><span className="round-label">SEGUNDO TURNO · 25/10/2026</span><p>Coleta programada para começar às 15h (Brasília).</p><small>Os resultados aparecerão somente quando publicados pelo TSE. Acervo independente do primeiro turno.</small></section>}
 {electionRound===1&&<section className={`round-banner ${majority?'round-majority':''}`} aria-label="Situação do primeiro turno"><span className="round-label">{round.mode==='waiting'?'PRIMEIRO TURNO':majority?'MAIORIA ABSOLUTA':round.tied?'EMPATE NA FAIXA DO 2º TURNO':round.final?'SEGUNDO TURNO PELOS TOTAIS':'CENÁRIO ATUAL DE 2º TURNO'}</span><p>{round.mode==='waiting'?'A sinalização aparecerá com os votos válidos publicados.':majority?<><strong>{roundNames[0]}</strong> tem mais da metade dos votos válidos {round.final?'ao fim da totalização.':'apurados até agora.'}</>:round.tied?'Há empate na posição de corte. A definição depende do resultado e do desempate oficial.':<>{roundNames.map((name,index)=><span key={name}>{index>0?' e ':''}<strong>{name}</strong></span>)} {round.final?'ocupam as duas primeiras posições.':'estão nas duas primeiras posições neste momento.'}</>}</p><small>{round.final?'Resultado conforme totais recebidos; confira a situação oficial no TSE.':'Sinalização provisória: pode mudar até o encerramento da totalização.'} A maioria absoluta exige mais de 50% dos votos válidos, excluindo brancos e nulos.</small></section>}
 <div className="ranking-title"><h2>Ranking da apuração</h2><span>{ranked.length?`${ranked.length} candidatos`:'Fonte: TSE'}</span></div><div className="sr-only" role="status" aria-live="polite">{notice}</div>
 <section className="race-grid" aria-label="Candidatos em ordem de votos">{ranked.map(({candidate:c,rank,index})=>{const leader=hasPlacement(c)&&index<2;const move=movement.find(m=>m.id===c.id);const delta=changes[c.id];const flagged=round.ids.includes(c.id);const label=electionRound===2?null:candidateStatus(c)?null:flagged?majority?(round.final?'Maioria absoluta':'Acima de 50% · parcial'):round.tied?'Empate no corte':round.final?'2º turno':'2º turno - Parcial':null;return <article ref={el=>{if(el)elements.current.set(c.id,el);else elements.current.delete(c.id);}} className={`race-card ${leader?'race-front':'race-compact'} `} key={c.id} aria-label={`${hasPlacement(c)?`${rank}ª posição, `:''}${c.name}, ${number(c.votes)} votos, ${percentage(c.percent)} por cento`}><div className="race-portrait">{leader?<CandidateAvatar candidate={c}/>:null}{hasPlacement(c)&&<span className="race-rank">{rank}<sup>º</sup></span>}<span className="race-party">{c.number} · {c.party}</span>{move&&<span className={`rank-up ${move.direction==='down'?'rank-down':''}`} role="img" aria-label={move.direction==='up'?'Subiu no ranking':'Desceu no ranking'}>{move.direction==='up'?<ArrowUp size={20}/>:<ArrowDown size={20}/>}</span>}</div><div className="race-card-body"><h3>{c.name}</h3><p className="race-identity-meta">{c.number} · {c.party}</p><div className="race-metrics"><div className="race-percent">{percentage(c.percent)}<span>%</span></div><div className="race-votes">{number(c.votes)} <span>votos</span></div><div className={`round-badge ${majority&&flagged?'majority-badge':''} ${!label?'round-badge-empty':''}`}>{label??' '}</div></div><div className="race-vote-track"><i style={{width:`${Math.min(100,Math.max(0,c.percent))}%`}}/></div>{delta!==undefined&&<p className={`race-delta ${delta<0?'negative':''}`}>{delta===0?'Sem mudança na última versão':`${delta>0?'+':''}${number(delta)} votos na última versão`}</p>}<div className="race-status"><CandidateStatus candidate={c}/>{[candidateStatus(c)?'':c.status,c.destination].filter(value=>value&&!/^v[aá]lido$/i.test(value.trim())).join(' · ')}</div><a className="race-audit-link" href={`${electionRound===2?'/segundo-turno':''}/painel?aba=auditoria&candidate=${encodeURIComponent(c.id)}`}><History size={14} aria-hidden="true"/><span>Ver histórico de alterações</span><ArrowUpRight size={14} aria-hidden="true"/></a></div></article>;})}</section>
 {!ranked.length&&<div className="race-empty"><Activity size={34}/><h2>{loading?'Buscando a primeira versão…':'Aguardando resultados do TSE'}</h2><p>Fotos, nomes e votos serão exibidos assim que os dados oficiais estiverem disponíveis.</p></div>}
 <section className="race-totals" aria-label="Totais oficiais"><div><span>Votos válidos</span><strong>{result?number(result.valid):'—'}</strong></div><div><span>Em branco</span><strong>{result?number(result.blank):'—'}</strong></div><div><span>Nulos</span><strong>{result?number(result.nullVotes):'—'}</strong></div></section>
 <section className="race-source"><div><Radio size={17}/><span>Última consulta ao TSE <strong>{data?.checked?new Date(data.checked).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—'} (Brasília){data?.http?` · HTTP ${data.http}`:''}</strong></span></div><div><Activity size={17}/><span>Intervalo real entre consultas <strong>{data?.cadence?.observedMs!=null?`${(data.cadence.observedMs/1000).toLocaleString('pt-BR',{maximumFractionDigits:2})} segundos`:'Aguardando duas consultas'} · pausa normal de 2 s + processamento</strong></span></div><div><Clock3 size={17}/><span>Geração no TSE <strong>{result?.generated??'—'}</strong></span></div><div><ShieldCheck size={17}/><span>Recebido pelo site <strong>{data?.archive?new Date(data.archive.received).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—'} (Brasília)</strong></span></div>{data?.source&&<a href={data.source} target="_blank" rel="noreferrer">Consultar arquivo oficial</a>}</section>
 <footer><strong>Fonte: Tribunal Superior Eleitoral · painel independente</strong><p>O ranking considera o total nacional, incluindo o exterior. Candidatos com 0% não exibem colocação. Empates em votos compartilham a posição; a ordem visual dos empatados é alfabética. Dados salvos como 1º turno - 2026. Coleta encerrada; o painel consulta o acervo preservado.</p><a href="/painel?aba=auditoria">Consultar auditoria, horários e versões preservadas</a></footer></div></main>;
}
