'use client';
import {roundFetch} from '../lib/round-client';
import {memo,useEffect,useMemo,useRef,useState} from 'react';
import {Plus,Minus,RotateCcw,X,ChevronLeft} from 'lucide-react';
import type {PresidentialMapCandidate,PresidentialMapState} from '../lib/presidential-map';
import {municipalFill} from '../lib/municipal';
import {candidateColor} from '../lib/candidate-colors';

type GeometryMunicipality={ibge:string;uf:string;municipio:string;name:string;path:string;center:number[]};
type Geometry={viewBox:string;edition:number;municipalities:GeometryMunicipality[];states:{uf:string;path:string;center:number[]}[]};
type MunicipalRow={ibge:string;uf:string;municipio:string;name:string;leaderId:string|null;leaderPercent:number|null;leaderVotes:number|null;tie:boolean;validVotes:number;progress:number;generated:string;received:string;checked:string;error:string|null;snapshotId:number;hash:string};
type MapData={candidates:PresidentialMapCandidate[];states:PresidentialMapState[];municipalities:MunicipalRow[];totalMunicipalities:number;collectedMunicipalities:number;collectionStatus?:{waiting:number;retrying:number;withoutVotes:number};checked?:string;error?:string};
type MunicipalVotes={municipalities:{ibge:string;name:string;uf:string;votes:number|null;percent:number|null;snapshotId?:number;generated?:string;received?:string}[];collected:number;total:number};
const number=(v:number)=>v.toLocaleString('pt-BR');
const percent=(v:number)=>`${v.toLocaleString('pt-BR',{maximumFractionDigits:2,minimumFractionDigits:1})}%`;
const local=(v:string)=>new Date(v).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',fractionalSecondDigits:3});
const externalLabels:Record<string,number[]>={RN:[1125,310],PB:[1125,368],PE:[1125,426],AL:[1125,484],SE:[1125,542],ES:[1125,760],RJ:[1125,830],DF:[800,575]};
const labelPositions:Record<string,number[]>={AC:[120,408],RO:[330,467],PA:[600,285],MA:[770,295],PI:[865,400],CE:[960,283],GO:[650,638],SP:[720,800],SC:[655,949]};
const MunicipalShapes=memo(function MunicipalShapes({geometry,rows,candidates}:{geometry:Geometry;rows:Map<string,MunicipalRow>;candidates:Map<string,PresidentialMapCandidate>}){return <g className="municipal-shapes">{geometry.municipalities.map(m=>{const row=rows.get(m.ibge),leader=row?.leaderId?candidates.get(row.leaderId):undefined;return <path key={m.ibge} d={m.path} fill={!row?'#303b45':!leader&&!row.tie?'#596775':municipalFill(leader,row?.leaderPercent??null,row?.tie??false)} fillRule="evenodd"/>;})}</g>;});
export default function PresidentialMap({version}:{version?:number}){
 const [geometry,setGeometry]=useState<Geometry|null>(null),[data,setData]=useState<MapData|null>(null),[error,setError]=useState(''),[scope,setScope]=useState('BR'),[active,setActive]=useState(''),[candidateId,setCandidateId]=useState(''),[detail,setDetail]=useState<MunicipalVotes|null>(null),[detailError,setDetailError]=useState(''),[busy,setBusy]=useState(false),[zoom,setZoom]=useState(1),[center,setCenter]=useState([630,605]);
 const svg=useRef<SVGSVGElement|null>(null),statePaths=useRef<Record<string,SVGPathElement|null>>({}),drag=useRef<{x:number;y:number;center:number[];moved:boolean}|null>(null);
 useEffect(()=>{const controller=new AbortController();roundFetch('/municipal-map.json',{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('Malha municipal indisponível.');return r.json() as Promise<Geometry>;}).then(setGeometry).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 useEffect(()=>{let active=true;const controller=new AbortController();async function refresh(){try{const r=await roundFetch('/api/auditoria/mapa',{cache:'no-store',signal:controller.signal});const j=await r.json() as MapData;if(!r.ok)throw Error(j.error);if(active){setData(j);setError('');}}catch(e){if(active&&!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'Mapa temporariamente indisponível.');}}refresh();return()=>{active=false;controller.abort();};},[version]);
 const rows=useMemo(()=>new Map(data?.municipalities.map(m=>[m.ibge,m])??[]),[data]);
 const candidates=useMemo(()=>new Map(data?.candidates.map(c=>[c.id,c])??[]),[data]);
 const states=useMemo(()=>new Map(data?.states.map(s=>[s.uf,s])??[]),[data]);
 const selected=states.get(active),selectedCandidate=candidates.get(candidateId);
 const sortedResults=selected?[...selected.results].sort((a,b)=>b.votes-a.votes):[];
 useEffect(()=>{if(!active||!candidateId){setDetail(null);return;}const controller=new AbortController();setBusy(true);setDetail(null);setDetailError('');roundFetch(`/api/auditoria/mapa/municipios?uf=${active}&candidato=${encodeURIComponent(candidateId)}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json() as MunicipalVotes&{error?:string};if(!r.ok)throw Error(j.error);setDetail({...j,municipalities:[...j.municipalities].sort((a,b)=>(b.percent??-1)-(a.percent??-1)||(b.votes??-1)-(a.votes??-1)||a.name.localeCompare(b.name,'pt-BR'))});}).catch(e=>{if(e.name!=='AbortError')setDetailError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[active,candidateId,data?.checked]);
 function showState(uf:string){setActive(uf);setCandidateId('');}
 function focusState(uf:string){setScope(uf);if(uf!=='BR')showState(uf);else{setActive('');setCandidateId('');}if(uf==='BR'){setZoom(1);setCenter([630,605]);return;}const box=statePaths.current[uf]?.getBBox();if(box){setCenter([box.x+box.width/2,box.y+box.height/2]);setZoom(Math.min(8,Math.max(1,Math.min(1100/box.width,1050/box.height))));}}
 function down(e:React.PointerEvent<SVGSVGElement>){if(zoom<=1)return;drag.current={x:e.clientX,y:e.clientY,center:[...center],moved:false};e.currentTarget.setPointerCapture(e.pointerId);}
 function move(e:React.PointerEvent<SVGSVGElement>){const d=drag.current;if(!d){if(e.pointerType==='mouse'&&!candidateId){const target=(e.target as SVGElement).closest('[data-uf]') as SVGElement|null;if(target?.dataset.uf&&target.dataset.uf!==active)showState(target.dataset.uf);}return;}const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.abs(dx)+Math.abs(dy)>5)d.moved=true;const width=e.currentTarget.getBoundingClientRect().width;setCenter([Math.max(630/zoom,Math.min(1260-630/zoom,d.center[0]-dx*1260/zoom/width)),Math.max(605/zoom,Math.min(1210-605/zoom,d.center[1]-dy*1260/zoom/width))]);}
 function up(e:React.PointerEvent<SVGSVGElement>){const wasDragged=drag.current?.moved;drag.current=null;if(wasDragged)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-uf]') as SVGElement|null;const uf=target?.dataset.uf;if(uf)showState(uf);else{setActive('');setCandidateId('');}}
 const width=1260/zoom,height=1210/zoom;
 return <section className="panel audit-map-section" aria-labelledby="audit-map-title"><div className="panel-title"><div><span className="eyebrow">PRESIDENTE · DISTRIBUIÇÃO MUNICIPAL</span><h2 id="audit-map-title">Mapa da votação por município</h2></div></div><p className="map-help">A cor indica quem lidera nos votos do município. Tons mais intensos representam percentuais maiores de votos válidos, de 0% a 100%. Passe sobre um estado ou toque para consultar os votos. Clique em um candidato para ver os municípios.</p>
 <div className="municipal-controls"><label>Estado<select value={scope} onChange={e=>focusState(e.target.value)}><option value="BR">Brasil inteiro</option>{geometry?.states.map(s=><option key={s.uf}>{s.uf}</option>)}</select></label></div>
 {data&&<p className="map-help"><strong>{number(data.collectedMunicipalities)} de {number(data.totalMunicipalities)} municípios com captura arquivada.</strong>{data.collectionStatus&&<span className="municipal-coverage-status">{number(data.collectionStatus.waiting)} sem captura arquivada · {number(data.collectionStatus.retrying)} com falha registrada · {number(data.collectionStatus.withoutVotes)} sem votos válidos</span>}</p>}
 {error&&<p className="alert" role="alert">{error}</p>}
 {!geometry||!data?<div className="map-loading">Carregando malha e capturas municipais…</div>:<><div className="municipal-legend-primary">{data.candidates.filter(c=>data.states.some(s=>s.results.some(r=>r.candidateId===c.id&&r.votes>0&&r.votes===Math.max(...s.results.map(v=>v.votes))))).slice(0,2).map(c=><span key={c.id}><i style={{background:candidateColor(c)}}/>{c.name}</span>)}<span><i style={{background:'#303b45'}}/>Ainda sem captura</span></div><details className="municipal-legend-more"><summary>Legenda completa e cobertura da coleta</summary><div className="map-legend">{data.candidates.map(c=><span key={c.id}><i style={{background:candidateColor(c)}}/>{c.name}</span>)}<span><i style={{background:'#a3a9b1'}}/>Empate em votos</span></div><p>Acervo do 1º turno - 2026, com coleta encerrada. Municípios diferentes podem ter horários de geração distintos. As áreas sem captura permanecem em cinza; cada município usa somente seu próprio resultado.</p></details><div className="municipal-map-board" onClick={event=>{if(event.target===event.currentTarget){setActive('');setCandidateId('');}}}><div className="municipal-zoom"><button aria-label="Ampliar mapa" onClick={()=>setZoom(z=>Math.min(10,z*1.5))}><Plus size={18}/></button><button aria-label="Reduzir mapa" onClick={()=>setZoom(z=>Math.max(1,z/1.5))}><Minus size={18}/></button><button aria-label="Mostrar Brasil inteiro" onClick={()=>focusState('BR')}><RotateCcw size={18}/></button></div><svg ref={svg} className="municipal-map-svg" viewBox={`${center[0]-width/2} ${center[1]-height/2} ${width} ${height}`} role="img" aria-label="Mapa da votação presidencial. Selecione um estado para consultar os votos." onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{drag.current=null;}} style={{touchAction:zoom>1?'none':'pan-y'}}>
 <MunicipalShapes geometry={geometry} rows={rows} candidates={candidates}/><g className="municipal-state-borders">{geometry.states.map(s=><path ref={el=>{statePaths.current[s.uf]=el;}} key={s.uf} d={s.path}/>)}</g>
 <g className="map-state-hitareas">{geometry.states.map(st=><path key={st.uf} d={st.path} data-uf={st.uf} className={active===st.uf?'active':''} tabIndex={0} role="button" aria-label={`Consultar votos de ${st.uf}`} onFocus={()=>showState(st.uf)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showState(st.uf);}}}/>)}</g>
 {zoom<=2.5&&<g className="municipal-state-labels state-only-labels">{geometry.states.map(st=>{const pos=externalLabels[st.uf]??labelPositions[st.uf]??st.center;return <g key={st.uf} data-uf={st.uf} transform={`translate(${pos[0]},${pos[1]})`}>{externalLabels[st.uf]&&<line x1={st.center[0]-pos[0]} y1={st.center[1]-pos[1]} x2="-32" y2="-7"/>}<rect x="-38" y="-27" width="92" height="54" rx="6"/><text x="-22" y="12">{st.uf}</text></g>;})}</g>}

 </svg><p className="municipal-map-tip">Passe sobre um estado ou toque para consultar</p>{active&&<div className="state-votes-tooltip" role="region" aria-label={`Votos em ${active}`}><div className="state-votes-heading"><div>{candidateId&&<button className="state-votes-back" onClick={()=>setCandidateId('')}><ChevronLeft size={16}/>Candidatos</button>}<span className="eyebrow">{active} · PRESIDENTE</span><h3>{selectedCandidate?.name??'Votação estadual'}</h3></div><button aria-label="Fechar votos do estado" onClick={()=>{setActive('');setCandidateId('');}}><X size={18}/></button></div>
 {!candidateId?<>{selected?<><p className="state-votes-meta">{percent(selected.progress)} das seções totalizadas · {number(selected.validVotes)} votos válidos</p><div className="state-votes-list">{sortedResults.map(r=>{const c=candidates.get(r.candidateId);return c?<button className="state-votes-row" key={c.id} onClick={()=>setCandidateId(c.id)}><span className="map-avatar">{c.photo?<img src={c.photo} alt=""/>:c.name.slice(0,1)}</span><span><strong>{c.name}</strong><small>{c.party} · {c.number}</small></span><span><strong>{percent(r.percent)}</strong><small>{number(r.votes)} votos</small></span></button>:null;})}</div><p className="state-votes-meta">Geração TSE: {selected.generated}<br/>Recebido: {local(selected.received)} (Brasília)</p></>:<p className="state-votes-meta">Ainda sem resultado estadual arquivado.</p>}</>:<>{busy&&<p className="state-votes-meta">Consultando votos por município…</p>}{detailError&&<p className="state-votes-meta" role="alert">{detailError}</p>}{detail&&<><p className="state-votes-meta">{number(detail.collected)} de {number(detail.total)} municípios com captura. Ordenados por percentual de votos, do maior para o menor. Percentuais sobre os votos válidos de cada município; os horários podem diferir do total estadual.</p><div className="state-votes-list municipal-votes-list">{detail.municipalities.map(m=><div className="state-votes-row municipal-votes-row" key={m.ibge}><span><strong>{m.name}</strong><small>{m.generated?`TSE: ${m.generated}`:'Aguardando captura'}{m.snapshotId&&<a href={`/api/municipios?ibge=${m.ibge}&id=${m.snapshotId}&download=1`}>Consultar versão</a>}</small></span><span><strong>{m.percent===null?'—':percent(m.percent)}</strong><small>{m.votes===null?'Sem dados':`${number(m.votes)} votos`}</small></span></div>)}</div></>}</>}
 </div>}</div></>}

 <p className="map-attribution">Malha municipal e estadual: IBGE, edição 2025, simplificada para visualização. Correspondência TSE–IBGE: configuração oficial de municípios das eleições 2026. <a href="/map-sources/provenance.json" target="_blank" rel="noreferrer">Fontes e hashes</a> · <a href="/painel?aba=logs&cargo=municipal&uf=BR">Logs da coleta municipal</a></p></section>;
}
