'use client';
import {useRound} from './RoundProvider';
import {BarChart3,ExternalLink,ChevronDown,Check,LockKeyhole} from 'lucide-react';
export type MenuSection='presidente'|'painel'|'exterior'|'auditoria'|'historico'|'logs'|'urnas'|'mcp';
export default function SiteHeader({active,uf='BR',cargo='1',includeExterior=true}:{active:MenuSection;uf?:string;cargo?:string;includeExterior?:boolean}){
 const round=useRound(),base=round===2?'/segundo-turno':'';
 const scope=`uf=${encodeURIComponent(uf)}&cargo=${encodeURIComponent(cargo)}&exterior=${includeExterior?1:0}`;
 const links:{id:MenuSection;href:string;label:string}[]=[{id:'presidente',href:base+'/',label:'Presidente'},{id:'painel',href:`${base}/painel?aba=resultados&${scope}`,label:'Outros resultados'},{id:'exterior',href:base+'/painel?aba=exterior&uf=ZZ&cargo=1',label:'Exterior'},{id:'auditoria',href:`${base}/painel?aba=auditoria&${scope}`,label:'Auditoria'},{id:'historico',href:`${base}/painel?aba=historico&${scope}`,label:'Histórico'},{id:'urnas',href:base+'/painel?aba=urnas',label:'Urnas'},{id:'logs',href:`${base}/painel?aba=logs&${scope}`,label:'Logs'},{id:'mcp',href:'/integracoes/mcp',label:'MCP'}];
 return <><header className="site-header"><div className="brand-selection"><a className="brand" href="/"><span className="brand-icon"><BarChart3 size={22}/></span>apuração<span className="brand-year">2026</span></a><details className="election-picker"><summary aria-label={`Escolher eleição: ${round}º turno - 2026`}><span><small>ELEIÇÃO</small><strong>{round}º turno - 2026</strong></span><ChevronDown size={16} aria-hidden="true"/></summary><div className="election-options" role="group" aria-label="Eleições disponíveis">{[1,2].map(r=><a key={r} className={`election-option ${round===r?'selected':''}`} href={r===1?'/':'/segundo-turno'} aria-current={round===r?'true':undefined}><span><strong>{r}º turno - 2026</strong><small>{r===1?'Apuração encerrada':'Coleta programada · 25/10 às 15h'}</small></span>{round===r?<Check size={17}/>:<ChevronDown size={15}/>}</a>)}</div></details></div><a className="official" href="https://resultados.tse.jus.br/oficial/app/index.html" target="_blank" rel="noreferrer">Fonte: TSE <ExternalLink size={15}/></a></header><nav className="site-menu" aria-label="Navegação principal">{links.map(link=><a key={link.id} className={link.id==='mcp'?'menu-mcp':undefined} href={link.href} aria-current={active===link.id?'page':undefined}>{link.label}</a>)}</nav></>;
}
