'use client';
import {useRound} from './RoundProvider';
import {roundFetch} from '../lib/round-client';
import {useEffect,useState} from 'react';
import {UFS} from '../lib/tse';
import Logs from './Logs';
import UrnCoverage from './UrnCoverage';
export default function Urnas(){const electionRound=useRound();
 const [uf,setUf]=useState('BR'),[m,setM]=useState(''),[z,setZ]=useState(''),[s,setS]=useState(''),[data,setData]=useState<any>(null),[error,setError]=useState(''),[before,setBefore]=useState<number|null>(null),[showLogs,setShowLogs]=useState(false);
 const query=`uf=${uf}${m?'&municipio='+m:''}${z?'&zona='+z:''}${s?'&secao='+s:''}${before?'&before='+before:''}`;
 useEffect(()=>{setData(null);let active=true;let timer:ReturnType<typeof setTimeout>;const c=new AbortController();async function read(){try{const r=await roundFetch('/api/urnas?'+query,{cache:'no-store',signal:c.signal});const j:any=await r.json();if(!r.ok)throw Error(j.error);if(active){setData(j);setError('');}}catch(e){if(active)setError(e instanceof Error?e.message:'Falha ao consultar urnas.');}finally{if(active)timer=setTimeout(read,10000);}}read();return()=>{active=false;c.abort();clearTimeout(timer);};},[query]);
 const changeUf=(value:string)=>{setUf(value);setM('');setZ('');setS('');setBefore(null);};
 const queue=(state:string)=>data?.queue?.find((r:any)=>r.state===state)?.n??0;
 return <section className="panel history"><UrnCoverage selected={uf} onSelect={changeUf}/><div className="panel-title"><div><span className="eyebrow">{electionRound}º TURNO · ARQUIVO ORIGINAL</span><h2>BU, RDV e logs das urnas</h2></div><button onClick={()=>setShowLogs(v=>!v)}>{showLogs?'Fechar logs de arquivos':'Logs de arquivos'}</button></div>
 <p className="history-help">Acervo do 1º turno - 2026. Download dos arquivos de urna em andamento; os resultados de votos permanecem congelados. Os índices oficiais identificam seções, recebimentos e nomes de arquivos. Arquivos de cada hash de recebimento ficam separados; todos os tipos anunciados pelo TSE são preservados.</p>
 <div className="urn-progress"><span><strong>{(data?.scopedSaved?.n??0).toLocaleString('pt-BR')}</strong> arquivos salvos · {uf==='BR'?'Brasil e exterior':uf==='ZZ'?'Exterior':uf}</span>{uf!=='BR'&&<span>{(data?.saved?.n??0).toLocaleString('pt-BR')} arquivos no acervo nacional</span>}<span>{((data?.scopedSaved?.bytes??0)/1048576).toFixed(2)} MB nesta seleção</span><span>{electionRound===2&&Date.now()<Date.parse('2026-10-25T18:00:00Z')?'Download programado para 25/10 às 15h':'Download de urnas ativo'}</span><span>{queue('pending')+queue('active')} tarefas pendentes / em processamento</span><span>{queue('retry')} aguardando nova tentativa</span></div>
 {data?.availableScopes?.some((r:any)=>r.saved>0)&&<div className="urn-available"><span>Arquivos arquivados em:</span>{data.availableScopes.filter((r:any)=>r.saved>0).map((r:any)=><button key={r.uf} type="button" onClick={()=>changeUf(r.uf)} aria-pressed={uf===r.uf}>{r.uf==='ZZ'?'Exterior':r.uf}<small>{r.saved.toLocaleString('pt-BR')}</small></button>)}</div>}
 {error&&<p className="alert" role="alert">{error}</p>}{!!data?.failures?.length&&<div className="alert"><strong>Arquivos aguardando disponibilidade ou nova tentativa</strong>{data.failures.map((r:any)=><p key={`${r.uf}:${r.kind}:${r.type}:${r.error}`}><b>{r.uf} · {r.type==='imgbu'?'Imagem do BU':r.type.toUpperCase()}</b> · {r.count} arquivo(s): {r.error}<br/><small>{r.next_ms<=Date.now()?'Prazo de espera cumprido; aguardando sua vez na fila.':<>Elegível para nova tentativa a partir de {new Date(r.next_ms).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} (Brasília)</>}<br/>Última tentativa: {new Date(r.updated).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} (Brasília)</small></p>)}<p>Os arquivos pendentes continuam na fila. Cada tentativa e a resposta original ficam preservadas nos logs.</p></div>}
 <div className="filters urn-filters"><label>Abrangência<select value={uf} onChange={e=>changeUf(e.target.value)}><option value="BR">Brasil e exterior · todas as UFs</option>{[...UFS,'ZZ'].map(u=><option key={u} value={u}>{u==='ZZ'?'Exterior':u}</option>)}</select></label><label>Município / localidade<select disabled={uf==='BR'} value={m} onChange={e=>{setM(e.target.value);setZ('');setS('');setBefore(null);}}><option value="">Todos</option>{data?.municipalities?.map((r:any)=><option key={r.municipio} value={r.municipio}>{r.municipio_name} · {r.municipio}</option>)}</select></label><label>Zona<select value={z} disabled={!m} onChange={e=>{setZ(e.target.value);setS('');setBefore(null);}}><option value="">Todas</option>{data?.zones?.map((r:any)=><option key={r.zona}>{r.zona}</option>)}</select></label><label>Seção<select value={s} disabled={!z} onChange={e=>{setS(e.target.value);setBefore(null);}}><option value="">Todas</option>{data?.sections?.map((r:any)=><option key={r.secao} value={r.secao}>{r.secao}{r.principal?' (agregada à '+r.principal+')':''}</option>)}</select></label></div>
 <div className="history-table"><table><thead><tr><th>Localização</th><th>Arquivo e recebimento TSE</th><th>Download / armazenamento</th><th>Consulta</th></tr></thead><tbody>{data?.files?.map((f:any)=><tr key={f.id}><td>{f.uf} · Município {f.municipio}<small>Zona {f.zona} · Seção {f.secao}</small><small>Pleito {f.pleito}</small></td><td><strong>{f.type}</strong><small>{f.filename}</small><small>Recebido no TSE: {f.tse_received??'Não informado'}</small><small>Situação TSE: {f.tse_status??'—'}</small><small className="urn-hash">Hash do recebimento: {f.tse_hash}</small></td><td>{f.state==='saved'?'Arquivado':'Download pendente'}<small>Download: {f.received?new Date(f.received).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—'}</small><small>Salvo: {f.saved?new Date(f.saved).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—'}</small><small>{f.size==null?'':f.size.toLocaleString('pt-BR')+' bytes'}</small><small className="urn-hash">SHA-256 da cópia: {f.sha256??'—'}</small></td><td>{f.state==='saved'?<a href={`/api/urnas?uf=${f.uf}&file=${f.id}`}>Baixar original</a>:<span>Aguardando download</span>}<a href={f.source} target="_blank" rel="noreferrer">Consultar no TSE</a>{f.log_id&&<a href={`/api/logs?uf=${f.uf}&cargo=urna&id=${f.log_id}&download=json`}>Baixar log da coleta</a>}</td></tr>)}</tbody></table></div>
 {!data?<p className="history-help" role="status">Consultando arquivos arquivados…</p>:!data.files?.length&&<div className="urn-empty"><p>Nenhum arquivo de urna foi arquivado para {uf==='BR'?'estes filtros':uf==='ZZ'?'o exterior':uf}{m?', município '+m:''}{z?', zona '+z:''}{s?', seção '+s:''}. O download continua em andamento. O percentual de apuração do TSE não representa a cobertura de download de BU, RDV e logs.</p>{uf!=='BR'&&<button type="button" onClick={()=>changeUf('BR')}>Ver arquivos de todas as UFs</button>}</div>}
 <div className="urn-pagination">{before&&<button onClick={()=>setBefore(null)}>Arquivos recentes</button>}{data?.next&&<button onClick={()=>setBefore(data.next)}>Arquivos anteriores</button>}</div>
 <p className="history-help">BU, RDV e log são arquivos técnicos, mantidos sem conversão. O hash do recebimento informado pelo TSE é distinto do SHA-256 calculado para a cópia. As assinaturas digitais não são verificadas nesta versão. O acervo só inclui arquivos efetivamente baixados; não há garantia de cobertura nacional completa nem de captura de todos os reenvios.</p>
 {showLogs&&<Logs uf={uf} cargo="urna"/>}
 </section>;
}
