'use client';
import {roundFetch} from '../lib/round-client';
import {useEffect,useState} from 'react';
import {UFS} from '../lib/tse';
import {UF_NAMES,type UrnState} from '../lib/urn-coverage';
export default function UrnCoverage({selected,onSelect}:{selected:string;onSelect:(uf:string)=>void}){
 const [states,setStates]=useState<UrnState[]>([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;const controller=new AbortController();async function read(){try{const response=await roundFetch('/api/urnas/apuracao',{cache:'no-store',signal:controller.signal});const data=await response.json() as {states:UrnState[];error?:string};if(!response.ok)throw Error(data.error??"Falha ao consultar apuração.");if(active){setStates(data.states);setError('');}}catch(e){if(active)setError(e instanceof Error?e.message:'Falha ao consultar apuração.');}}read();return()=>{active=false;controller.abort();};},[]);
 return <div className="uf-coverage"><span className="eyebrow">27 UNIDADES DA FEDERAÇÃO</span><h2>Apuração por UF</h2><p>Percentual oficial de seções totalizadas para presidente, no 1º turno. Clique em uma UF para consultar seus arquivos de urna.</p>{error&&<p className="alert" role="alert">{error}</p>}<div className="uf-grid">{UFS.map(uf=>{const state=states.find(row=>row.uf===uf);return <button type="button" key={uf} className="uf-card" aria-pressed={selected===uf} onClick={()=>onSelect(uf)}><span className="uf-card-heading"><strong>{uf}</strong><span>{UF_NAMES[uf]}</span></span><strong className="uf-percent">{state?.progress==null?'—':state.progress.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%'}</strong><span className="uf-meter" role="progressbar" aria-label={`Seções totalizadas em ${UF_NAMES[uf]}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={state?.progress??undefined}><span style={{width:`${Math.min(100,Math.max(0,state?.progress??0))}%`}}/></span><span className="uf-count">{state?.sections==null?'Aguardando dados oficiais':`${state.sections.toLocaleString('pt-BR')} / ${state.totalSections?.toLocaleString('pt-BR')} seções`}</span>{state?.generated&&<small>TSE: {state.generated} · Brasília</small>}{state?.received&&<small>Capturado: {new Date(state.received).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} · Brasília</small>}</button>;})}</div><p className="uf-note">Dados arquivados do 1º turno - 2026. Este percentual representa a apuração do TSE; a quantidade de arquivos baixados aparece abaixo.</p></div>;
}
