'use client';
import {useRound} from '../RoundProvider';
import SecondPump from '../SecondPump';
import {roundFetch} from '../../lib/round-client';
import {useEffect,useRef,useState} from 'react';
import {Activity,BarChart3,RefreshCw,Radio,Clock3,ExternalLink,ShieldCheck} from 'lucide-react';
import SiteHeader from '../SiteHeader';
import ResultCandidate from '../ResultCandidate';
import {ranking} from '../../lib/presidential';
import ResultCoverage from '../ResultCoverage';
import History from '../History';
import Audit from '../Audit';
import Logs from '../Logs';
import Urnas from '../Urnas';
import UrnPump from '../UrnPump';
import {PanelView,panelTitles} from '../../lib/panel-view';
import {CARGOS,UFS,Result} from '../../lib/tse';
type Data={composition?:{sources:{uf:string;snapshotId:number;generated:string;received:string;hash:string}[]};result:Result|null;error:string|null;source:string;checked:string;latency:number;http:number;nextPoll:number;archive?:{id:number;idg:string;hash:string;received:string;saved:string}|null};
type Event={id:string;time:string;observed:string;changes:{name:string;delta:number}[]};
const number=(v:number)=>v.toLocaleString('pt-BR');
const percent=(v:number)=>v.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function Panel({initial}:{initial:PanelView}){const electionRound=useRound();
 const [menu,setMenu]=useState(initial.menu),[includeExterior,setIncludeExterior]=useState(initial.includeExterior??true);
 const isResults=menu==='painel'||menu==='exterior';const title=panelTitles[menu];
 const [uf,setUf]=useState(initial.uf),[cargo,setCargo]=useState(initial.cargo),[data,setData]=useState<Data|null>(null),[events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[search,setSearch]=useState(''),[auditCandidate]=useState(initial.candidate);

 const selected=useRef('');const previous=useRef<Result|null>(null);const previousHash=useRef('');
 useEffect(()=>{if(menu==='urnas'||(menu==='logs'&&cargo==='municipal')){setLoading(false);return;}let stopped=false;const controller=new AbortController();const selection=uf+':'+cargo+':'+includeExterior;if(selected.current!==selection){selected.current=selection;previous.current=null;previousHash.current='';setEvents([]);setData(null);}setLoading(true);
 async function poll(){let delay=2000;try{
 const response=await roundFetch(uf==='BR'&&cargo==='1'&&!includeExterior?'/api/resultados/brasil':`/api/resultados?uf=${uf}&cargo=${cargo}`,{signal:controller.signal,cache:'no-store'});const next:Data=await response.json();if(!response.ok)throw Error(next.error??'Falha ao consultar o serviço.');if(stopped)return;
 const current=next.result;
 if(current&&previous.current&&current.generationTime<previous.current.generationTime){delay=2000;}else{
 if(current&&previousHash.current!==(next.archive?.hash??current.id)){
 const old=previous.current;
 if(old){const changes=current.candidates.map(c=>{const last=old.candidates.find(o=>o.id===c.id);return {name:c.name,delta:last?c.votes-last.votes:c.votes};}).filter(c=>c.delta!==0);
 setEvents(list=>[{id:`${next.archive?.hash??current.id}:${next.checked}`,time:current.generated,observed:new Date().toLocaleTimeString('pt-BR'),changes},...list].slice(0,100));}
 previousHash.current=next.archive?.hash??current.id;previous.current=current;
 }setData(next);delay=next.nextPoll??2000;}
 }catch(err){if(!stopped)setData(old=>({...old,result:old?.result??null,error:err instanceof Error?err.message:'Falha de conexão.',source:old?.source??'',checked:old?.checked??'',latency:0,http:0,nextPoll:15000}));delay=15000;}
 finally{if(!stopped){setLoading(false);if(electionRound===2)setTimeout(poll,Math.max(2000,delay));}}}
 poll();return()=>{stopped=true;controller.abort();};},[uf,cargo,includeExterior,retry,menu==='urnas',menu==='logs']);
 const result=data?.result;const candidates=ranking(result?.candidates??[]).filter(({candidate:c})=>`${c.name} ${c.party} ${c.number}`.toLowerCase().includes(search.toLowerCase()));
 const changeUf=(value:string)=>{setUf(value);if(menu==='painel'||menu==='exterior')setMenu(value==='ZZ'?'exterior':'painel');if(['BR','ZZ'].includes(value)&&!(menu==='logs'&&cargo==='municipal'))setCargo('1');else if(cargo==='8'||cargo==='7')setCargo(value==='DF'?'8':'7');};
 return <main><UrnPump/><SecondPump/>
 <SiteHeader active={menu} uf={uf} cargo={cargo} includeExterior={includeExterior}/>
 <div className="workspace"><div className="title-row"><div><div className="eyebrow">ELEIÇÕES GERAIS · {electionRound}º TURNO</div><h1>{title.title}</h1><p className="subtitle">{title.description}</p></div>{isResults&&<div className={`connection ${data?.error?'warning':''}`}><Radio size={17}/>{loading?'Carregando acervo':data?.error?'Conexão indisponível':electionRound===2?'2º turno · atualização automática':'1º turno encerrado'}</div>}</div>
 {menu!=='urnas'&&<section className="filters"><label>Abrangência<select disabled={menu==='exterior'} value={uf} onChange={e=>changeUf(e.target.value)}><option value="BR">Brasil</option><option value="ZZ">Exterior</option>{UFS.map(u=><option key={u}>{u}</option>)}</select></label><label>Cargo<select value={cargo} onChange={e=>setCargo(e.target.value)}>{menu==='logs'&&<option value="municipal">Presidente · municípios</option>}{Object.entries(CARGOS).filter(([c])=>electionRound===1||['1','3'].includes(c)).filter(([c])=>['BR','ZZ'].includes(uf)?c==='1':c==='8'?uf==='DF':c==='7'?uf!=='DF':true).map(([c,n])=><option key={c} value={c}>{n}</option>)}</select></label>{(isResults||menu==='historico'||menu==='auditoria')&&uf==='BR'&&cargo==='1'&&<label className="include-exterior"><input type="checkbox" checked={includeExterior} onChange={e=>setIncludeExterior(e.target.checked)}/><span>Incluir exterior</span></label>}<div className="filter-meta"><span>{electionRound===2?'25 de outubro de 2026':'04 de outubro de 2026'}</span><strong>{uf==='BR'?(includeExterior?'Brasil + exterior':'Brasil sem exterior'):uf==='ZZ'?'Votação no exterior':`Estado · ${uf}`}</strong></div><button disabled={loading} onClick={()=>setRetry(r=>r+1)}><RefreshCw size={17}/> Atualizar</button></section>}
 {isResults&&data?.error&&<div className="alert" role="alert"><strong>Não foi possível obter uma atualização.</strong> {data.error} {result?'Os últimos dados recebidos permanecem abaixo.':'Nenhum resultado foi substituído por dados fictícios.'}</div>}
 {isResults&&<><section className="summary"><div className="progress-card"><div className="card-label"><Activity size={17}/> SEÇÕES TOTALIZADAS</div><div className="big-number">{result?percent(result.progress):'—'}<span>%</span></div><div className="progress"><i style={{width:`${Math.min(100,result?.progress??0)}%`}}/></div><p>{result?`${number(result.sections)} de ${number(result.totalSections)} seções`:'Aguardando dados do TSE'}</p></div><div className="stat"><span>Votos válidos</span><strong>{result?number(result.valid):'—'}</strong><small>{result?.status??'Resultado ainda indisponível'}</small></div><div className="stat"><span>Votos em branco</span><strong>{result?number(result.blank):'—'}</strong><small>Conforme total oficial</small></div><div className="stat"><span>Votos nulos</span><strong>{result?number(result.nullVotes):'—'}</strong><small>Inclui nulos técnicos</small></div></section>
 <div className="columns presidential"><section className="results panel"><div className="panel-title"><div><span className="eyebrow">{CARGOS[cargo].toUpperCase()} · {uf}</span><h2>Votação dos candidatos</h2></div><span className="partial">{result?.status==='Totalização finalizada'?'Finalizada':'Parcial'}</span></div><input className="search" placeholder="Buscar nome, partido ou número" aria-label="Buscar candidato" value={search} onChange={e=>setSearch(e.target.value)}/>
 <div className="result-candidates">{candidates.length?candidates.map(({candidate:c,rank,index})=><ResultCandidate includeExterior={includeExterior} key={c.id} candidate={c} rank={rank} leader={c.percent>0&&index<2} uf={uf} cargo={cargo} delta={events[0]?.changes.find(e=>e.name===c.name)?.delta}/>):<div className="empty"><BarChart3 size={34}/><h3>{loading?'Consultando resultados…':search?'Nenhum candidato encontrado':'Aguardando resultados oficiais'}</h3><p>{search?'Tente outro nome ou número.':'Os candidatos e os votos aparecerão quando o arquivo oficial estiver disponível.'}</p></div>}</div>
 <div className="source-note"><ShieldCheck size={16}/>{data?.composition?'Total calculado a partir das 27 UFs, sem exterior. Percentuais recalculados; os arquivos têm horários próprios.':'Valores e situação de votação recebidos do TSE.'}</div>{data?.composition&&<details className="composition-sources"><summary>Consultar as 27 versões usadas neste total</summary><p>Este total calculado pode diferir da atualização nacional por usar arquivos estaduais publicados em horários diferentes. Os arquivos originais permanecem preservados.</p><a href={data.source} target="_blank" rel="noreferrer">Consultar esta composição em JSON</a>{data.composition.sources.map(source=><a key={source.uf} href={`/api/historico?uf=${source.uf}&cargo=1&id=${source.snapshotId}&download=1`}>{source.uf} · Geração {source.generated} · Registro {source.snapshotId}</a>)}</details>}</section>
 <aside><section className="panel feed"><div className="panel-title"><div><span className="eyebrow">NESTA SESSÃO</span><h2>Atualizações recebidas</h2></div><Clock3 size={20}/></div><p className="feed-intro">Diferenças entre os totais consultados. A primeira consulta estabelece a base.</p>{events.length?events.map(e=><div className="event" key={e.id}><div className="event-time">TSE · {e.time}</div><small>Recebida às {e.observed} · ID {e.id}</small>{e.changes.length?e.changes.map((c,i)=><p key={i}><span>{c.name}</span><strong className={c.delta<0?'negative':''}>{c.delta>0?'+':''}{number(c.delta)}</strong></p>):<p>Arquivo atualizado sem mudança nos votos dos candidatos.</p>}</div>):<div className="feed-empty"><Activity size={26}/><p>As próximas versões recebidas aparecerão aqui.</p></div>}</section><section className="sync"><span className="eyebrow">SINCRONIZAÇÃO</span><dl><dt>Última consulta</dt><dd>{data?.checked?new Date(data.checked).toLocaleTimeString('pt-BR'):'—'}</dd><dt>Geração no TSE</dt><dd>{result?.generated??'—'}</dd><dt>Recebido pelo site</dt><dd>{data?.archive?new Date(data.archive.received).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}):'—'}</dd><dt>Arquivo salvo</dt><dd>{data?.composition?'27 versões estaduais':data?.archive?`Registro ${data.archive.id}`:'—'}</dd><dt>Resposta da fonte</dt><dd>{data?.http?`HTTP ${data.http} · ${data.latency} ms`:'—'}</dd><dt>Intervalo normal</dt><dd>{electionRound===2?'Consulta a cada 2 segundos, respeitando pausas':'Coleta encerrada'}</dd></dl>{data?.source&&<a href={data.source} target="_blank" rel="noreferrer">{data?.composition?'Consultar composição':'Abrir arquivo oficial'} <ExternalLink size={14}/></a>}</section></aside></div>
 {menu==='painel'&&<ResultCoverage/>}</>}
 <div id="archive" className="internal-view">{menu==='urnas'?<Urnas/>:menu==='logs'?<Logs uf={uf} cargo={cargo}/>:menu==='auditoria'?<Audit includeExterior={includeExterior} selectedCandidate={auditCandidate} uf={uf} cargo={cargo} candidates={result?.candidates??[]} version={data?.archive?.id}/>:menu==='historico'?<History includeExterior={includeExterior} uf={uf} cargo={cargo} version={data?.archive?.id}/>:null}</div><footer><strong>Fonte: Tribunal Superior Eleitoral</strong><p>Este é um painel independente. Os arquivos contêm totais acumulados; a sequência de cada voto e versões entre consultas não são disponibilizadas por este painel. A atualização depende da publicação do TSE, da rede e do intervalo de consulta. O histórico da sessão mostra as últimas 100 versões; o arquivo persistente permite consultar todas as versões coletadas e salvas. A coleta ocorre enquanto o painel está aberto. Não é possível recuperar versões intermediárias que não foram recebidas.</p><a href="https://www.tse.jus.br/eleicoes/informacoes-tecnicas-sobre-a-divulgacao-de-resultados" target="_blank" rel="noreferrer">Documentação técnica de 2026 <ExternalLink size={13}/></a></footer></div>
 </main>;
}
