import {electionContext} from './election-context';
import {getStorage} from '../db';
import {crc32,localHeader,descriptor,centralHeader,endRecords,concat} from './zip64';
const PART=16*1024*1024;
function paths(){const round=electionContext().round,ROOT=`exports/2026-${round}`;return {ROOT,STATE:ROOT+'/state.json',ZIP:ROOT+`/tse-${round}-turno-2026.zip`};}
export const inventory=`WITH objects AS (SELECT object_key,size FROM collection_logs WHERE object_key IS NOT NULL UNION ALL SELECT object_key,size FROM urn_files WHERE state='saved' AND object_key IS NOT NULL UNION ALL SELECT object_key,NULL size FROM snapshots UNION ALL SELECT object_key,NULL size FROM municipal_snapshots) SELECT object_key,MAX(COALESCE(size,0)) size FROM objects GROUP BY object_key`;
type State={phase:'files'|'central'|'ready'|'error';uploadId:string;parts:{partNumber:number;etag:string}[];cursor:string;count:number;offset:number;pending?:string;centralPending?:string;centralChunks:string[];centralSize:number;centralOffset:number;centralIndex:number;step:number;size?:number;error?:string;generated?:string};
export async function exportStatus(){const {STATE}=paths();const {db,bucket}=getStorage();const [jobs,indices,unsaved,total,stateObj]=await Promise.all([db.prepare("SELECT state,count(*) n FROM urn_jobs GROUP BY state").all<{state:string;n:number}>(),db.prepare("SELECT count(DISTINCT uf) n FROM urn_jobs WHERE kind='index' AND state='done'").first<{n:number}>(),db.prepare("SELECT count(*) n FROM urn_files WHERE state<>'saved'").first<{n:number}>(),db.prepare(`SELECT count(*) count,sum(size) bytes FROM (${inventory})`).first<{count:number;bytes:number}>(),bucket.get(STATE)]);const pending=jobs.results.filter(j=>j.state!=='done').reduce((n,j)=>n+j.n,0),complete=(indices?.n??0)===28&&pending===0&&(unsaved?.n??0)===0;const state=stateObj?await stateObj.json<State>():null;return {count:total?.count??0,bytes:total?.bytes??0,pending,missingFiles:unsaved?.n??0,indicesCompleted:indices?.n??0,indicesTotal:28,collectionComplete:complete,phase:state?.phase??'waiting',packedFiles:state?.count??0,zipBytes:state?.size??null,error:state?.error??null,ready:complete&&state?.phase==='ready'};}
export async function prepareExport(){const {ROOT,STATE,ZIP}=paths();const status=await exportStatus();if(!status.collectionComplete||status.ready)return status;const {db,bucket}=getStorage(),now=Date.now(),lease=crypto.randomUUID();await db.prepare('INSERT INTO source_state(source,next_ms,lease_until) VALUES (?,0,0) ON CONFLICT(source) DO NOTHING').bind('archive-zip-2026-1').run();const acquired=await db.prepare('UPDATE source_state SET lease=?,lease_until=? WHERE source=? AND lease_until<? RETURNING source').bind(lease,now+120000,'archive-zip-2026-1',now).first();if(!acquired)return {...status,busy:true};
 let state:State|undefined;let baseline:string|undefined;
 try{const previous=await bucket.get(STATE);state=previous?await previous.json<State>():undefined;if(!state){const upload=await bucket.createMultipartUpload(ZIP,{httpMetadata:{contentType:'application/zip',contentDisposition:`attachment; filename="tse-${electionContext().round}-turno-2026.zip"`}});state={phase:'files',uploadId:upload.uploadId,parts:[],cursor:'',count:0,offset:0,centralChunks:[],centralSize:0,centralOffset:0,centralIndex:0,step:0};await bucket.put(STATE,JSON.stringify(state));}
 baseline=JSON.stringify(state);delete state.error;
 if(state.phase==='central'){const existing=await bucket.head(ZIP);if(existing&&existing.size===state.centralOffset+state.centralSize+98){state.phase='ready';state.size=existing.size;await bucket.put(STATE,JSON.stringify(state));return {...status,phase:'ready',ready:true};}}
 const upload=bucket.resumeMultipartUpload(ZIP,state.uploadId);const oldPending=state.pending,oldCentral=state.centralPending;let pending=state.pending?new Uint8Array(await (await bucket.get(state.pending))!.arrayBuffer()):new Uint8Array();let central=state.centralPending?new Uint8Array(await (await bucket.get(state.centralPending))!.arrayBuffer()):new Uint8Array();
 async function append(bytes:Uint8Array){let pos=0;while(pos<bytes.length){const length=Math.min(PART-pending.length,bytes.length-pos);pending=concat([pending,bytes.subarray(pos,pos+length)]);pos+=length;state!.offset+=length;if(pending.length===PART){if(state!.parts.length>=10000)throw Error('Pacote excedeu o limite de partes.');const part=await upload.uploadPart(state!.parts.length+1,pending);state!.parts.push(part);pending=new Uint8Array();}}}
 if(state.phase==='files'){const rows=await db.prepare(`SELECT * FROM (${inventory}) WHERE object_key>? ORDER BY object_key LIMIT 64`).bind(state.cursor).all<{object_key:string;size:number}>();let consumed=0;for(const row of rows.results){if(Date.now()-now>20000)break;const object=await bucket.get(row.object_key);if(!object)throw Error('Original indisponível: '+row.object_key);const offset=state.offset;await append(localHeader(row.object_key));let crc=0xffffffff,size=0;const reader=object.body.getReader();try{while(true){const chunk=await reader.read();if(chunk.done)break;crc=crc32(chunk.value,crc);size+=chunk.value.length;await append(chunk.value);}}finally{reader.releaseLock();}crc=(crc^0xffffffff)>>>0;await append(descriptor(crc,size));const entry=centralHeader(row.object_key,crc,size,offset);central=concat([central,entry]);state.centralSize+=entry.length;state.count++;state.cursor=row.object_key;consumed++;if(central.length>=512*1024){const key=`${ROOT}/central/${state.centralChunks.length}.bin`;await bucket.put(key,central);state.centralChunks.push(key);central=new Uint8Array();}}
 if(rows.results.length<64&&consumed===rows.results.length){if(central.length){const key=`${ROOT}/central/${state.centralChunks.length}.bin`;await bucket.put(key,central);state.centralChunks.push(key);central=new Uint8Array();}state.phase='central';state.centralOffset=state.offset;}}
 else if(state.phase==='central'){for(let i=0;i<16&&state.centralIndex<state.centralChunks.length;i++){const object=await bucket.get(state.centralChunks[state.centralIndex]);if(!object)throw Error('Índice interno do ZIP indisponível.');await append(new Uint8Array(await object.arrayBuffer()));state.centralIndex++;}if(state.centralIndex===state.centralChunks.length){await append(endRecords(state.count,state.centralSize,state.centralOffset));if(pending.length){state.parts.push(await upload.uploadPart(state.parts.length+1,pending));pending=new Uint8Array();}await upload.complete(state.parts);state.phase='ready';state.size=state.offset;state.generated=new Date().toISOString();}}
 state.step++;state.pending=pending.length?`${ROOT}/pending/${state.step}.bin`:undefined;state.centralPending=central.length?`${ROOT}/central-pending/${state.step}.bin`:undefined;if(state.pending)await bucket.put(state.pending,pending);if(state.centralPending)await bucket.put(state.centralPending,central);await bucket.put(STATE,JSON.stringify(state));for(const key of [oldPending,oldCentral].filter(Boolean) as string[]){try{await bucket.delete(key);}catch(error){console.warn('Limpeza temporária do ZIP',error);}}return {...status,phase:state.phase,packedFiles:state.count,ready:state.phase==='ready'};
 }catch(error){if(baseline){const restored=JSON.parse(baseline) as State;restored.error=error instanceof Error?error.message:String(error);await bucket.put(STATE,JSON.stringify(restored));}throw error;}finally{await db.prepare('UPDATE source_state SET lease=NULL,lease_until=0 WHERE source=? AND lease=?').bind('archive-zip-2026-1',lease).run();}}
export async function downloadExport(){const {ZIP}=paths();const status=await exportStatus();if(!status.ready)return Response.json({error:'O ZIP será liberado após todos os arquivos e índices serem baixados e o pacote estar pronto.',status},{status:409});const {bucket}=getStorage();const object=await bucket.get(ZIP);if(!object)return Response.json({error:'Pacote indisponível.'},{status:503});return new Response(object.body,{headers:{'Content-Type':'application/zip','Content-Disposition':`attachment; filename="tse-${electionContext().round}-turno-2026.zip"`,'Content-Length':String(object.size),'Cache-Control':'private, no-store'}});}
