import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const snapshots=sqliteTable('snapshots',{
 id:integer('id').primaryKey({autoIncrement:true}), source:text('source').notNull(), uf:text('uf').notNull(), cargo:text('cargo').notNull(),idg:text('idg').notNull(),generationMs:integer('generation_ms').notNull(),generated:text('generated').notNull(),totalization:text('totalization').notNull(),received:text('received').notNull(),saved:text('saved').notNull(),hash:text('hash').notNull(),objectKey:text('object_key').notNull(),normalized:text('normalized').notNull(),etag:text('etag'),modified:text('modified')
},t=>[uniqueIndex('snapshot_identity').on(t.source,t.idg,t.hash),index('snapshot_scope').on(t.uf,t.cargo,t.id)]);
export const sourceState=sqliteTable('source_state',{source:text('source').primaryKey(),nextMs:integer('next_ms').notNull(),lease:text('lease'),leaseUntil:integer('lease_until').notNull().default(0),error:text('error'),checked:text('checked'),http:integer('http'),latency:integer('latency')});
export const collectionLogs=sqliteTable('collection_logs',{
 id:integer('id').primaryKey({autoIncrement:true}),source:text('source').notNull(),uf:text('uf').notNull(),cargo:text('cargo').notNull(),started:text('started').notNull(),received:text('received'),finished:text('finished'),state:text('state').notNull(),http:integer('http'),latency:integer('latency'),size:integer('size'),hash:text('hash'),objectKey:text('object_key'),snapshotId:integer('snapshot_id'),idg:text('idg'),generated:text('generated'),totalization:text('totalization'),requestHeaders:text('request_headers').notNull(),responseHeaders:text('response_headers'),error:text('error')
},t=>[index('logs_scope').on(t.uf,t.cargo,t.id)]);
export const urnJobs=sqliteTable('urn_jobs',{id:integer('id').primaryKey({autoIncrement:true}),key:text('job_key').notNull(),kind:text('kind').notNull(),uf:text('uf').notNull(),source:text('source'),payload:text('payload').notNull(),state:text('state').notNull().default('pending'),nextMs:integer('next_ms').notNull().default(0),leaseUntil:integer('lease_until').notNull().default(0),attempts:integer('attempts').notNull().default(0),error:text('error'),updated:text('updated').notNull()},t=>[uniqueIndex('urn_job_unique').on(t.key),index('urn_job_queue').on(t.state,t.nextMs)]);
export const urnSections=sqliteTable('urn_sections',{id:integer('id').primaryKey({autoIncrement:true}),pleito:text('pleito').notNull(),uf:text('uf').notNull(),municipio:text('municipio').notNull(),municipioName:text('municipio_name').notNull(),zona:text('zona').notNull(),secao:text('secao').notNull(),principal:text('principal'),auxGenerated:text('aux_generated'),metadata:text('metadata').notNull()},t=>[uniqueIndex('urn_section_scope').on(t.pleito,t.uf,t.municipio,t.zona,t.secao)]);
export const urnFiles=sqliteTable('urn_files',{id:integer('id').primaryKey({autoIncrement:true}),pleito:text('pleito').notNull(),uf:text('uf').notNull(),municipio:text('municipio').notNull(),zona:text('zona').notNull(),secao:text('secao').notNull(),tseHash:text('tse_hash').notNull(),filename:text('filename').notNull(),type:text('type').notNull(),tseReceived:text('tse_received'),tseStatus:text('tse_status'),source:text('source').notNull(),objectKey:text('object_key'),sha256:text('sha256'),size:integer('size'),received:text('received'),saved:text('saved'),logId:integer('log_id'),state:text('state').notNull().default('pending')},t=>[uniqueIndex('urn_file_version').on(t.pleito,t.uf,t.municipio,t.zona,t.secao,t.tseHash,t.filename),index('urn_file_scope').on(t.uf,t.municipio,t.zona,t.secao,t.id)]);

export const auditEvents=sqliteTable('audit_events',{id:integer('id').primaryKey({autoIncrement:true}),uf:text('uf').notNull(),cargo:text('cargo').notNull(),logId:integer('log_id').notNull(),snapshotId:integer('snapshot_id').notNull(),previousId:integer('previous_id'),eventKey:text('event_key').notNull(),kind:text('kind').notNull(),candidate:text('candidate'),name:text('name').notNull(),beforeVotes:integer('before_votes'),afterVotes:integer('after_votes'),delta:integer('delta'),received:text('received').notNull()},t=>[uniqueIndex('audit_observation').on(t.logId,t.eventKey),index('audit_scope').on(t.uf,t.cargo,t.id),index('audit_candidate').on(t.uf,t.cargo,t.candidate,t.id)]);
export const resultJobs=sqliteTable('result_jobs',{source:text('source').primaryKey(),uf:text('uf').notNull(),cargo:text('cargo').notNull(),nextMs:integer('next_ms').notNull().default(0),leaseUntil:integer('lease_until').notNull().default(0),checked:text('checked'),http:integer('http'),error:text('error'),snapshotId:integer('snapshot_id')},t=>[index('result_job_queue').on(t.nextMs,t.leaseUntil)]);

export const municipalJobs=sqliteTable('municipal_jobs',{ibge:text('ibge').primaryKey(),ordinal:integer('ordinal').notNull().default(0),uf:text('uf').notNull(),municipio:text('municipio').notNull(),name:text('name').notNull(),source:text('source').notNull(),nextMs:integer('next_ms').notNull().default(0),leaseUntil:integer('lease_until').notNull().default(0),checked:text('checked'),http:integer('http'),error:text('error'),snapshotId:integer('snapshot_id'),summary:text('summary')},t=>[index('municipal_job_queue').on(t.nextMs,t.leaseUntil),uniqueIndex('municipal_scope').on(t.uf,t.municipio)]);
export const municipalSnapshots=sqliteTable('municipal_snapshots',{id:integer('id').primaryKey({autoIncrement:true}),ibge:text('ibge').notNull(),uf:text('uf').notNull(),municipio:text('municipio').notNull(),source:text('source').notNull(),idg:text('idg').notNull(),generationMs:integer('generation_ms').notNull(),generated:text('generated').notNull(),received:text('received').notNull(),saved:text('saved').notNull(),hash:text('hash').notNull(),objectKey:text('object_key').notNull(),normalized:text('normalized').notNull(),etag:text('etag'),modified:text('modified'),logId:integer('log_id').notNull()},t=>[uniqueIndex('municipal_version').on(t.ibge,t.idg,t.hash),index('municipal_history').on(t.ibge,t.generationMs,t.id)]);
